name: Update Website

on:
  push:
    branches:
      - main

jobs:
  update-website:
    runs-on: windows-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update website
        run: |
          cd .
          git pull origin main
